export const source = {
    "example.my.rcp.three.model:Diagram":{
        "xmlns:example.my.rcp.three.model":"http:///example/my/rcp/nodeemf.ecore",
        "nodes":[
            {
                "x":"189",
                "y":"155",
                "name":"开始",
                "inputs":"/0/@nodes.1/@outputs.0",
                "id":"b81e8b50ff99405cbf1af5a11c1b8ee6",
                "nodeType":"BEGIN",
                "inputParams":"[]",
                "outputParams":"[]"
            },
            {
                "x":"189",
                "y":"274",
                "name":"流程1",
                "inputs":"/0/@nodes.3/@outputs.0",
                "id":"5827cbddb9f04628b544ec28890b832f",
                "nodeType":"RECTANGLE",
                "inputParams":"[]",
                "outputParams":"[]",
                "outputs":{
                    "source":"/0/@nodes.1",
                    "target":"/0/@nodes.0"
                }
            },
            {
                "x":"189",
                "y":"504",
                "name":"结束",
                "id":"829589bdc9704d3dad794ad21e309d5d",
                "nodeType":"END",
                "inputParams":"[]",
                "outputParams":"[]",
                "outputs":{
                    "source":"/0/@nodes.2",
                    "target":"/0/@nodes.3"
                }
            },
            {
                "x":"189",
                "y":"384",
                "name":"流程2",
                "inputs":"/0/@nodes.2/@outputs.0",
                "id":"8d696e5f6e1340688194969a0ca55777",
                "nodeType":"RECTANGLE",
                "inputParams":"[]",
                "outputParams":"[]",
                "outputs":{
                    "source":"/0/@nodes.3",
                    "target":"/0/@nodes.1"
                }
            },
            {
                "x":"189",
                "y":"198",
                "name":"开始",
                "inputs":"/0/@nodes.7/@outputs.0",
                "id":"b603157770404aafa71ed067858adc79",
                "nodeType":"BEGIN",
                "parentId":"5827cbddb9f04628b544ec28890b832f",
                "inputParams":"[]",
                "outputParams":"[]"
            },
            {
                "x":"189",
                "y":"528",
                "name":"结束",
                "id":"d7259f64103d46f78cd72abfdac67b03",
                "nodeType":"END",
                "parentId":"5827cbddb9f04628b544ec28890b832f",
                "inputParams":"[]",
                "outputParams":"[]",
                "outputs":{
                    "source":"/0/@nodes.5",
                    "target":"/0/@nodes.6"
                }
            },
            {
                "x":"189",
                "y":"443",
                "name":"重复",
                "inputs":"/0/@nodes.5/@outputs.0",
                "id":"9534c3440eec43b58434aac657415227",
                "nodeType":"TECH_COMPONENT",
                "parentId":"5827cbddb9f04628b544ec28890b832f",
                "targetFunction":"com.grgbanking.gmbp.components.technology.ExampleCompGroup.repeat",
                "compoentLevel":"平台",
                "compoentDesc":"对输入的字符串进行复制重复",
                "compoentExplain":"主键注释",
                "compoentGroup":"组件组",
                "inputParams":"[{\"comment\":\"输入的字符串\",\"name\":\"b\",\"paramName\":\"输入的字符串(String.class)\",\"paramValue\":\"12\",\"type\":\"String.class\"}]",
                "outputParams":"[{\"comment\":\"返回的字符串\",\"name\":\"string\",\"paramName\":\"返回的字符串(String.class)\",\"paramValue\":\"12\",\"type\":\"String.class\"}]",
                "outputs":{
                    "source":"/0/@nodes.6",
                    "target":"/0/@nodes.7"
                }
            },
            {
                "x":"189",
                "y":"315",
                "name":"账户信息查询",
                "inputs":"/0/@nodes.6/@outputs.0",
                "id":"b609c2fb6a764b668fddeadaf2950a6b",
                "nodeType":"TECH_COMPONENT",
                "parentId":"5827cbddb9f04628b544ec28890b832f",
                "targetFunction":"com.grgbanking.gmbp.components.technology.ExampleCompGroup.add",
                "compoentLevel":"平台",
                "compoentDesc":"对输入的值进行自增",
                "compoentExplain":"主键注释",
                "compoentGroup":"组件组",
                "inputParams":"[{\"name\":\"交易日期\",\"value\":\"__REQ__TransactionDate\",\"level\":\"TRACE\"},{\"name\":\"交易时间\",\"value\":\"__REQ__TransactionTime\",\"level\":\"TRACE\"},{\"name\":\"交易机构\",\"value\":\"__REQ__TradingInstitutions\",\"level\":\"TRACE\"},{\"name\":\"交易柜员\",\"value\":\"__REQ__TradingTellers\",\"level\":\"TRACE\"},{\"name\":\"渠道流水号\",\"value\":\"__REQ__ChannelSerialNumber\",\"level\":\"TRACE\"},{\"name\":\"账号/卡号\",\"value\":\"__REQ__AccountNumberAndCardNumber\",\"level\":\"TRACE\"},{\"name\":\"产品类型\",\"value\":\"__REQ__ProductType\",\"level\":\"TRACE\"},{\"name\":\"币种\",\"value\":\"__REQ__Currency\",\"level\":\"TRACE\"},{\"name\":\"账户序号\",\"value\":\"__REQ__AccountSerialNumber\",\"level\":\"TRACE\"}]",
                "outputParams":"[{\"name\":\"处理结果\",\"value\":\"__REQ__ProcessResults\",\"level\":\"TRACE\"},{\"name\":\"处理结果码\",\"value\":\"__REQ__ProcessResultsCode\",\"level\":\"TRACE\"},{\"name\":\"处理信息\",\"value\":\"__REQ__ProcessingInformation\",\"level\":\"TRACE\"},{\"name\":\"返回信息数组\",\"value\":\"__REQ__ProcessArrayInformation\",\"level\":\"TRACE\"},{\"name\":\"流水\",\"value\":\"__REQ__Flow\",\"level\":\"TRACE\"}]",
                "outputs":{
                    "source":"/0/@nodes.7",
                    "target":"/0/@nodes.4"
                }
            },
            {
                "x":"189",
                "y":"516",
                "name":"结束",
                "id":"087a5d2cfdbb4546916434b8d67a71ed",
                "nodeType":"END",
                "parentId":"8d696e5f6e1340688194969a0ca55777",
                "inputParams":"[]",
                "outputParams":"[]",
                "outputs":{
                    "source":"/0/@nodes.8",
                    "target":"/0/@nodes.10"
                }
            },
            {
                "x":"189",
                "y":"173",
                "name":"开始",
                "inputs":"/0/@nodes.11/@outputs.0",
                "id":"538317d5656745b3afea2829680be8e8",
                "nodeType":"BEGIN",
                "parentId":"8d696e5f6e1340688194969a0ca55777",
                "inputParams":"[]",
                "outputParams":"[]"
            },
            {
                "x":"189",
                "y":"432",
                "name":"自增",
                "inputs":"/0/@nodes.8/@outputs.0",
                "id":"b5d78758f7084b7480affbb32846aab3",
                "nodeType":"TECH_COMPONENT",
                "parentId":"8d696e5f6e1340688194969a0ca55777",
                "targetFunction":"com.grgbanking.gmbp.components.technology.ExampleCompGroup.add",
                "compoentLevel":"平台",
                "compoentDesc":"对输入的值进行自增",
                "compoentExplain":"主键注释",
                "compoentGroup":"组件组",
                "inputParams":"[{\"comment\":\"输入的值\",\"name\":\"input\",\"paramName\":\"输入的值(Integer.class)\",\"paramValue\":\"22\",\"type\":\"Integer.class\"},{\"comment\":\"输入的值\",\"name\":\"a\",\"paramName\":\"输入的值(Integer.class)\",\"paramValue\":\"22\",\"type\":\"Integer.class\"}]",
                "outputParams":"[{\"comment\":\"返回的值\",\"name\":\"output\",\"paramName\":\"返回的值(Integer.class)\",\"paramValue\":\"23\",\"type\":\"Integer.class\"}]",
                "outputs":{
                    "source":"/0/@nodes.10",
                    "target":"/0/@nodes.11"
                }
            },
            {
                "x":"189",
                "y":"276",
                "name":"重复",
                "inputs":"/0/@nodes.10/@outputs.0",
                "id":"a4ab9885185f4ffc9a867e5e3c67512a",
                "nodeType":"TECH_COMPONENT",
                "parentId":"8d696e5f6e1340688194969a0ca55777",
                "targetFunction":"com.grgbanking.gmbp.components.technology.ExampleCompGroup.repeat",
                "compoentLevel":"平台",
                "compoentDesc":"对输入的字符串进行复制重复",
                "compoentExplain":"主键注释",
                "compoentGroup":"组件组",
                "inputParams":"[{\"name\":\"b\",\"paramName\":\"输入的字符串(String.class)\",\"paramValue\":\"22\",\"type\":\"String.class\",\"comment\":\"输入的字符串\"}]",
                "outputParams":"[{\"name\":\"string\",\"paramName\":\"返回的字符串(String.class)\",\"paramValue\":\"22\",\"type\":\"String.class\",\"comment\":\"返回的字符串\"}]",
                "outputs":{
                    "source":"/0/@nodes.11",
                    "target":"/0/@nodes.9"
                }
            }
        ]
    }
}